### ISSUE TITLE
[NOT bug!, sort of] Cant work with HTML summary/details tag

### ISSUE THREAD

**Issue by ccchan234** [foenixx/anki-incremental-reveal-card#2]
hi,
in addition of cloze 1 by 1, i also want to have tree like text, foldable at every level.

one way is to use HTML summary/details tag like:

<details>
 <summary>
  2-MIS
 </summary>
 <ul>
  <details>
   <summary>
    RADIATION
   </summary>
   <ul>
    <details>
     <summary>
      ind
     </summary>
     <ul>
      <details>
       <summary>
        if surgery failed, then
       </summary>
       <ul>
        <li>
         med +/- radiation
        </li>
       </ul>
      </details>
      <li>
       for large invasive tumor
      </li>
      <li>
       if CI to surgery
      </li>
     </ul>
    </details>
    <details>
     <summary>
      type
     </summary>
     <ul>
      <li>
       conventional radiotherapy
      </li>
      <li>
       stereotactic radiosurgery
      </li>
     </ul>
    </details>
    <li>
     may hypo Pit
    </li>
    <details>
     <summary>
      complication?
     </summary>
     <ul>
      <li>
       radio vasculo pathy? &gt;&gt;&gt;???
      </li>
     </ul>
    </details>
   </ul>
  </details>
 </ul>
</details>

and this will show collapsable in the buildin cloze note type.
![image](https://github.com/foenixx/anki-incremental-reveal-card/assets/37549409/656ea709-1ca0-454d-a4d3-d249760e3da4)

![image](https://github.com/foenixx/anki-incremental-reveal-card/assets/37549409/02e47163-7d4c-44a1-aaea-5286eea3f771)

would be nice if can have both of them, thanks

**Comment by ccchan234** [comment]
the code of the above tree:

`

<details>
 <summary>
  2-MIS
 </summary>
 <ul>
  <details>
   <summary>
    RADIATION
   </summary>
   <ul>
    <details>
     <summary>
      ind
     </summary>
     <ul>
      <details>
       <summary>
        if surgery failed, then
       </summary>
       <ul>
        <li>
         med +/- radiation
        </li>
       </ul>
      </details>
      <li>
       for large invasive tumor
      </li>
      <li>
       if CI to surgery
      </li>
     </ul>
    </details>
    <details>
     <summary>
      type
     </summary>
     <ul>
      <li>
       conventional radiotherapy
      </li>
      <li>
       stereotactic radiosurgery
      </li>
     </ul>
    </details>
    <li>
     may hypo Pit
    </li>
    <details>
     <summary>
      complication?
     </summary>
     <ul>
      <li>
       radio vasculo pathy? &gt;&gt;&gt;???
      </li>
     </ul>
    </details>
   </ul>
  </details>
 </ul>
</details>


`

**Comment by foenixx** [comment]
Hi,

What's the actual problem? It doesn't reveal clozes inside html summary\detail tags?

**Comment by ccchan234** [comment]
1. win10+anki v2.1.54+qt6+your cloze template working happily
2. if that tree is inside the cloze, then the cloze cannot be revealed, thus turns the cloze 1 by 1 into normal cloze
3. if that tree is outside the cloze, then the cloze 1 by 1 is still normal

final: so looks like the tree is too large/complex, that the cloze 1 by 1 cant process.

but it's ok, as the tree is collapsible, it can be put outside the cloze and still dont reveal anser.

**Comment by ccchan234** [comment]
hi, i just checked,

if the cloze contains 1 details/summary pair only,
it do can still be reveal 1 by 1.

this still work as reveal 1 by 1:
![image](https://github.com/foenixx/anki-incremental-reveal-card/assets/37549409/d12626df-acea-422e-9a34-06cc42412822)

**Comment by ccchan234** [comment]
hi, i have troubleshooted something for you
1. indeep your cloze-1-by-1 works very well
2. even the "tree text" is inside the cloze-1-by-1, your cloze-1-by-1 should still work: 
3. but if the tree is made with enter/breaks (i dont sure which, i show you the code later), then the cloze-1-by-1 wont work, and function as the native cloze

do not work:
![image](https://github.com/foenixx/anki-incremental-reveal-card/assets/37549409/ed0e8682-77c1-4198-a07f-3cc940615e5c)



work:
![image](https://github.com/foenixx/anki-incremental-reveal-card/assets/37549409/2b3bc444-5917-46d3-8c41-3a23fce3d449)

**Comment by ccchan234** [comment]
ok, so it's my tree text's source's problem, not this cloze note type's.
i'll close the issue then.
thx for input.
